export const LOAD_HOME_PAGE_DATA_SUCCESS = 'LOAD_HOME_PAGE_DATA_SUCCESS';
export const LOADED_TOASTER_INFO_SUCCESS = 'LOADED_TOASTER_INFO_SUCCESS';
export const LOADED_DATA_SUCCESS = 'LOADED_DATA_SUCCESS';
export const LOADED_DIALOGOPEN_SUCCESS = 'LOADED_DIALOGOPEN_SUCCESS';
export const LOAD_PAGE_DATA_SUCCESS = 'LOAD_PAGE_DATA_SUCCESS';
export const NETWORK_REQUEST_STATUS = 'NETWORK_REQUEST_STATUS';
export const TABLE_HEAD_REQUEST_STATUS = 'TABLE_HEAD_REQUEST_STATUS';
export const LOAD_FILTER_HOME_PAGE_DATA_SUCCESS =
  'LOAD_FILTER_HOME_PAGE_DATA_SUCCESS';
