export const LOAD_HOME_PAGE_DATA_SUCCESS = 'LOAD_HOME_PAGE_DATA_SUCCESS';
export const LOADED_TOASTER_INFO_SUCCESS = 'LOADED_TOASTER_INFO_SUCCESS';
export const LOAD_PAGINATION_DATA_SUCCESS = 'LOAD_PAGINATION_DATA_SUCCESS';
export const LOADED_DATA_SUCCESS = 'LOADED_DATA_SUCCESS';
